// Para birimi seçenekleri
export const CURRENCIES = [
  { code: "usd", symbol: "$", label: "USD" },
  { code: "eur", symbol: "€", label: "EUR" },
  { code: "try", symbol: "₺", label: "TRY" },
];

// Logonun mor/camgöbeği paletinden türetilen açık tema
export const lightTheme = {
  bg: "#F4F7FF",
  homeBg: "#EDF3FF",
  card: "#FFFFFF",
  cardShadow: "#243B73",
  cardShadowOpacity: 0.1,
  text: "#0B1530",
  subtext: "#5F7094",
  border: "#D9E4F7",
  header: "#F9FBFF",
  searchBg: "#EAF1FF",
  accent: "#6E4CFF",
  accentSecondary: "#0BBFEA",
  accentLight: "#EDE9FF",
  chipActiveBg: "#6E4CFF",
  chipActiveText: "#FFFFFF",
  chipInactiveBg: "#E6EEFC",
  chipInactiveText: "#536589",
  pillPosBg: "#DDF8F0",
  pillNegBg: "#FFE3EB",
  favActive: "#F43F7F",
  favInactive: "#7F91B5",
  activityIndicator: "#0BBFEA",
  error: "#BE123C",
};

// Varsayılan tema: logo ile aynı gece laciverti, mor ve camgöbeği
export const darkTheme = {
  bg: "#050914",
  homeBg: "#070D1B",
  card: "#0D1830",
  cardShadow: "#000000",
  cardShadowOpacity: 0.28,
  text: "#F7F9FF",
  subtext: "#8EA2C7",
  border: "#1B2B50",
  header: "#081126",
  searchBg: "#0C1830",
  accent: "#8B5CF6",
  accentSecondary: "#2DDCFF",
  accentLight: "#1C1648",
  chipActiveBg: "#7C4DFF",
  chipActiveText: "#FFFFFF",
  chipInactiveBg: "#14213D",
  chipInactiveText: "#9AAED1",
  pillPosBg: "#0E332F",
  pillNegBg: "#3D1425",
  favActive: "#FF5A91",
  favInactive: "#6F83AA",
  activityIndicator: "#2DDCFF",
  error: "#FF8BAB",
};
